use_frameworks!
inhibit_all_warnings!

def appstore_pods
    pod 'Easy', :path => '../'
    pod 'Easy/Common', :path => '../'
    pod 'Easy/PageController', :path => '../'
    pod 'Easy/RSA', :path => '../'
    pod 'Easy/Social', :path => '../'
    pod 'Easy/Scan', :path => '../'
    pod 'Easy/PhotoBrowser', :path => '../'
    sdk_pods
end

def sdk_pods
    
end

def beta_pods
    pod 'EasyBeta', :path => '../../'
end

target 'Easy_Example' do
  appstore_pods

  target 'Easy_Tests' do
    inherit! :search_paths
  end
end

target 'Easy_Example_Beta' do
    appstore_pods
    beta_pods
end
