use_frameworks!
inhibit_all_warnings!

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 10.0
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
      end
      if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
        target.build_configurations.each do |config|
            config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        end
      end
    end
  end
end

def appstore_pods
    pod 'Easy', :path => '../'
    pod 'Easy/Common', :path => '../'
    pod 'Easy/PageController', :path => '../'
    pod 'Easy/RSA', :path => '../'
    pod 'Easy/Social', :path => '../'
    pod 'Easy/Scan', :path => '../'
    sdk_pods
end

def sdk_pods
    
end

def beta_pods
    pod 'EasyBeta', :path => '../../EasyBeta'
end

target 'Easy_Example' do
  appstore_pods

  target 'Easy_Tests' do
    inherit! :search_paths
  end
end

target 'Easy_Example_Beta' do
    appstore_pods
    beta_pods
end
