use_frameworks!

target 'Easy_Example' do
  pod 'Easy', :path => '../'
  pod 'Easy/Common', :path => '../'
  pod 'Easy/Page', :path => '../'
  pod 'Easy/Social', :path => '../'
  pod 'Easy/Scan', :path => '../'

  target 'Easy_Tests' do
    inherit! :search_paths
  end
end

target 'Easy_Example_Beta' do
    pod 'Easy', :path => '../'
    pod 'Easy/Common', :path => '../'
    pod 'Easy/Page', :path => '../'
    pod 'Easy/Social', :path => '../'
    pod 'Easy/Scan', :path => '../'
    pod 'Easy/Beta', :path => '../'
end
