# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
osx_image: xcode12.4
branches:
  only: master
  
# cache: cocoapods
# podfile: Example/Podfile
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example
script:
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/Easy.xcworkspace -scheme Easy_Example -destination 'platform=iOS Simulator,name=iPhone 6,OS=9.0' | xcpretty
# - pod lib lint

notifications:
  email: false
